repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ['--write-changes', '--uri-ignore-words-list=ist']
        exclude: CHANGELOG\.rst|\.(svg|pyc|drawio)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-xml
        - id: check-ast

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
        - id: codespell
          name: codespell
          description: Checks for common misspellings in text files.
          entry: codespell  *
          language: python
          types: [text]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=120", "--preview"]