repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        exclude_types: [json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: check-merge-conflict
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-xml
        - id: check-ast

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
        - id: codespell
          name: codespell
          description: Checks for common misspellings in text files.
          language: python
          types: [text]
          args: ["--skip=*.ipynb", "-L Arent, ARENT"]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length=120", "--preview"]
